# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors = ["yasssine <yassine.bna@proton.me>"]
name = "mplayer-server"
version = "0.1.1"
edition = "2021"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/yassinebenarbia/mplayer-server"
description = "Simple dbus server to play music"
keywords = ["music", "server", "mplayer-server", "mplayer-client", "linux", "dbus", "zbus", "audio", "playback", "mplayer"]

[dependencies]
zbus = { version = "5.11.0", features = ["tokio"] }
serde = { version = "1.0.204", features = ["serde_derive"] }
lofty = "0.21.0"
regex = "1.11.0"
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tokio = { version = "1.43.0", features = ["full"] }
rand = "0.9.0"
nucleo = "0.5.0"
serde_json = "1.0.141"
rodio = { version = "0.21.1", features = ["symphonia-all"] }

[features]
full-log = []
trivial = []
debug = []
