path = "/home/user/Music/" # path to media DIRECTORY
sort = "ByDurationDescending" # ByTitleAscending, ByTitleDescending, ByDurationAscending, ByDurationDescending, Shuffle 
repeat = "AllMusics" # Dont, ThisMusic
volume = 0.9 # value beteen 0.0 and 1.0
allow_formats = ["ogg", "flac", "mp3"] # webm, still not supported tho
